Repository bottle-note/bottle-note-frontend, pull requests merged in 2024-05, with the labels that each got.

#36 [#32] 리스트 컴포넌트 - 매니저 컴포넌트 UI 스타일 변경
  public/options-icon.svg
  src/app/(primary)/user/[id]/_constants/index.ts
  src/app/(primary)/user/[id]/page.tsx
  src/components/ListManager.tsx
Labels: Style

#41 [#22] 소셜 로그인 OAuth Server 연동
  src/app/(custom)/login/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
Labels: Feat, Modify

#44 위클리 핫5 api 연동 및 디자인 변경 적용
  .github/workflows/code-review.yml
  next.config.mjs
  package.json
  src/app/(primary)/_components/CategoryList.tsx
  src/app/(primary)/_components/Header.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/components/HorizontalItem.tsx
  src/components/HorizontalScroll.tsx
  src/components/SearchBar.tsx
  src/constants/common.ts
  src/types/Alcohol.ts
Labels: Modify, Style, Refactor

#45 [Fix] Remove duplicate single quotes from hostname
  next.config.mjs
Labels: Fix

#46 Home page.tsx 서버 컴포넌트로 만들기 위한 컴포넌트 분리
  src/app/(primary)/_components/HotList.tsx
  src/app/(primary)/page.tsx
  src/constants/common.ts
Labels: Refactor

#47 Search alcohol details 퍼블리싱(리뷰 리스트 제외)
  public/arrowLeft.svg
  public/edit-white.svg
  public/externalLink.svg
  public/like-filled-white.svg
  public/starWhite.svg
  src/app/(primary)/_components/BackHeader.tsx
  src/app/(primary)/_components/FlavorTag.tsx
  src/app/(primary)/_components/HotList.tsx
  src/app/(primary)/_components/Label.tsx
  src/app/(primary)/search/[category]/[id]/layout.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/(primary)/search/[category]/page.tsx
  src/app/(primary)/search/[id]/page.tsx
  src/components/HorizontalScroll.tsx
  src/components/Star.tsx
  yarn.lock
Labels: Style, Refactor

#49 [#32, #43] /search 검색페이지 UI/UX 작업
  mock/alcohol.ts
  public/Close_Sub_Coral.svg
  src/app/(primary)/_components/RecentSearch.tsx
  src/app/(primary)/search/[category]/page.tsx
  src/app/(primary)/search/_components/SearchList.tsx
  src/app/(primary)/search/layout.tsx
  src/app/(primary)/search/page.tsx
  src/app/(primary)/user/[id]/_components/UserInfo.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/components/CategorySelector.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/List/ListManager.tsx
  src/components/SearchBar.tsx
  src/style/globals.css
Labels: Feat, Style

#51 [#26, #48] Alcohol details에 리뷰 리스트 퍼블리싱 및 API 연결
  next.config.mjs
  public/bottle.svg
  public/commentFull.svg
  public/commentOutline.svg
  public/ellipsis.svg
  public/glass.svg
  public/thumbUpCoral.svg
  public/thumbUpOutline.svg
  public/thumbUpWhite.svg
  public/user_img.png
  src/app/(primary)/_components/BackHeader.tsx
  src/app/(primary)/_components/FlavorTag.tsx
  src/app/(primary)/_components/HotList.tsx
  src/app/(primary)/_components/Label.tsx
  src/app/(primary)/_components/SubHeader.tsx
  src/app/(primary)/_components/Toggle.tsx
  src/app/(primary)/comment/[id]/page.tsx
  src/app/(primary)/comment/modify/page.tsx
  src/app/(primary)/comment/register/page.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/[category]/[id]/layout.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/reviews/page.tsx
  src/components/LinkButton.tsx
  src/types/Alcohol.ts
  src/types/Review.ts
  src/utils/formatDate.ts
  src/utils/formatNum.ts
  tailwind.config.ts
Labels: Feat, Modify, Style, Refactor

#55 [#42] 소셜 로그인 및 백엔드 로그인/회원가입 api 연동
  mock/alcohol.ts
  src/app/(primary)/search/[category]/page.tsx
  src/app/(primary)/search/page.tsx
  src/app/api/AlcholsApi.ts
  src/app/api/AuthApi.ts
  src/app/api/alcohols/route.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/components/BackDrop.tsx
  src/components/List/ListManager.tsx
  src/hooks/useBlockScroll.ts
  src/middleware.ts
  src/types/Alcohol.ts
  src/types/Auth.ts
  src/types/common.ts
  src/utils/apiWrapper.ts
  src/utils/getAccessToken.ts
Labels: Feat

#56 [#52] 리뷰 리스트 더보기 페이지 페블리싱
  public/arrowLeftCoral.svg
  public/empty_bottle.svg
  src/app/(primary)/_components/EmptyView.tsx
  src/app/(primary)/_components/SubHeader.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/search/[category]/[id]/_components/ReportModal.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/reviews/page.tsx
  src/style/globals.css
  src/types/Alcohol.ts
  src/types/LinkButton.ts
Labels: Feat, Modify, Style, Refactor
