Repository bottle-note/bottle-note-frontend, pull requests merged in 2024-12, with the labels that each got.

#191 [#190] API 응답 처리 전 중복 요청 방지 로직 구현 및 review 리팩토링
  src/app/(custom)/layout.tsx
  src/app/(primary)/_components/Header.tsx
  src/app/(primary)/_components/SubHeader.tsx
  src/app/(primary)/inquire/register/page.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/rating/page.tsx
  src/app/(primary)/report/_constants/index.ts
  src/app/(primary)/report/page.tsx
  src/app/(primary)/review/_components/TagsForm.tsx
  src/app/(primary)/review/_schemas/reviewFormSchema.ts
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/(primary)/search/page.tsx
  src/components/Button.tsx
  src/components/Navbar.tsx
  src/hooks/useAlcoholDetails.ts
  src/hooks/useCallOnce.ts
  src/hooks/useErrorModal.ts
Labels: Feat, Fix, Style, Refactor

#199 [#196] Review 디자인, 로직 변경 및 오류 수정
  public/bottle_note_Icon_logo.svg
  public/bottle_note_Icon_logo_white.svg
  public/icon/arrow-down-subcoral.svg
  public/icon/arrow-up-subcoral.svg
  public/icon/plus-subcoral.svg
  public/icon/questionmark-gray.svg
  public/icon/questionmark-subcoral.svg
  public/icon/reset-mainGray.svg
  src/app/(primary)/_components/Header.tsx
  src/app/(primary)/_components/SubHeader.tsx
  src/app/(primary)/inquire/register/page.tsx
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/AddressForm.tsx
  src/app/(primary)/review/_components/AlcoholInfo.tsx
  src/app/(primary)/review/_components/KakaoAddressMap.tsx
  src/app/(primary)/review/_components/OptionsContainer.tsx
  src/app/(primary)/review/_components/PriceForm.tsx
  src/app/(primary)/review/_components/SelectFlavor.tsx
  src/app/(primary)/review/_components/TagsForm.tsx
  src/app/(primary)/review/_components/form/AddressForm.tsx
  src/app/(primary)/review/_components/form/ContentForm.tsx
  src/app/(primary)/review/_components/form/ImagesForm.tsx
  src/app/(primary)/review/_components/form/PriceForm.tsx
  src/app/(primary)/review/_components/form/RatingForm.tsx
  src/app/(primary)/review/_components/form/ReviewForm.tsx
  src/app/(primary)/review/_components/form/TagsForm.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/reviews/page.tsx
  src/app/(primary)/search/layout.tsx
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/components/HoverTouchBox.tsx
  src/components/Navbar.tsx
  src/types/types.d.ts
Labels: Feat, Modify, Fix, Style, Refactor

#205 [#204] 회원탈퇴/게스트 로그인 api 연동
  src/app/(custom)/login/page.tsx
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/app/(primary)/user/[id]/_constants/index.ts
  src/app/api/AuthApi.ts
  src/app/api/UserApi.ts
Labels: Feat

#203 [#194] Review 임시저장 기능 구현
  src/app/(primary)/_components/Header.tsx
  src/app/(primary)/review/register/page.tsx
  src/components/Toast.tsx
  src/hooks/useReviewAutoSave.ts
  src/hooks/useToast.tsx
  src/types/Review.ts
Labels: Feat, Style
