Repository bottle-note/bottle-note-frontend, pull requests merged in 2024-04, with the labels that each got.

#16 Create layout UI for UserPage
  __tests__/page.test.tsx
  public/like-filled.svg
  public/like-outline.svg
  src/app/(custom)/layout.tsx
  src/app/(custom)/login/page.tsx
  src/app/(primary)/category/[id]/page.tsx
  src/app/(primary)/comment/[id]/page.tsx
  src/app/(primary)/comment/modify/page.tsx
  src/app/(primary)/comment/register/page.tsx
  src/app/(primary)/detail/[id]/comments/page.tsx
  src/app/(primary)/detail/[id]/page.tsx
  src/app/(primary)/error/page.tsx
  src/app/(primary)/inquire/page.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/rating/page.tsx
  src/app/(primary)/report/page.tsx
  src/app/(primary)/search/page.tsx
  src/app/(primary)/user/[id]/_components/LikeBtn.tsx
  src/app/(primary)/user/[id]/_components/ListItem.tsx
  src/app/(primary)/user/[id]/_components/Star.tsx
  src/app/(primary)/user/[id]/follower/page.tsx
  src/app/(primary)/user/[id]/following/page.tsx
  src/app/(primary)/user/[id]/history/page.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/app/user/[id]/page.tsx
  tailwind.config.ts
Labels: Style

#17 Add Searchbar, weekly hot5 and navbar
  public/home.svg
  public/user.svg
  public/whiskey_img1.png
  src/app/(primary)/_components/Header.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/page.tsx
  src/app/layout.tsx
  src/components/CategoryTitle.tsx
  src/components/HorizontalItem.tsx
  src/components/HorizontalScroll.tsx
  src/components/Navbar.tsx
  src/components/PostCard.tsx
  src/components/SearchBar.tsx
  src/components/Star.tsx
  tailwind.config.ts
Labels: Modify, Style, Refactor

#18 Added category list and updated design
  public/arrowRight.svg
  public/bg_category.jpg
  public/category_whisky1.png
  src/app/(primary)/_components/CategoryList.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/search/[id]/page.tsx
  src/components/CategoryTitle.tsx
  src/components/HorizontalItem.tsx
  src/components/HorizontalScroll.tsx
  src/components/LinkButton.tsx
  src/components/Navbar.tsx
  src/components/SearchBar.tsx
  src/components/Star.tsx
  src/types/Alcohol.ts
  src/types/LinkButton.ts
  tailwind.config.ts
Labels: Feat, Style, Refactor

#20 Create layout UI for UserPage #12
  .eslintignore
  .eslintrc.js
  next.config.mjs
  public/Logo_2.png
  public/Logo_2.svg
  public/Menu_Sub_Coral.svg
  public/profile-default.svg
  public/review.svg
  src/app/(primary)/layout.tsx
  src/app/(primary)/user/[id]/_components/HistoryOverview.tsx
  src/app/(primary)/user/[id]/_components/LikeBtn.tsx
  src/app/(primary)/user/[id]/_components/ListItem.tsx
  src/app/(primary)/user/[id]/_components/ReviewBtn.tsx
  src/app/(primary)/user/[id]/_components/Star.tsx
  src/app/(primary)/user/[id]/_components/UserInfo.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/components/ListItem.tsx
  src/components/ListManager.tsx
  src/utils/truncStr.ts
  tailwind.config.ts
Labels: Style

#29 디자인과 다른 home page 부분 수정
  src/app/(primary)/_components/Header.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/components/CategoryTitle.tsx
  src/components/HorizontalItem.tsx
  src/components/LinkButton.tsx
  src/components/Navbar.tsx
  src/components/SearchBar.tsx
  src/components/Star.tsx
Labels: Style
