Repository bottle-note/bottle-note-frontend, pull requests merged in 2024-06, with the labels that each got.

#57 [#50] 별점 페이지 퍼블리싱 #50
  public/star-half.svg
  public/star-outline.svg
  public/star.svg
  src/app/(primary)/rating/layout.tsx
  src/app/(primary)/rating/page.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/List/ListItemRating.tsx
  src/components/StarRaiting.tsx
  src/utils/addNewLine.ts
Labels: Feat, Style

#58 [#38] Review/[id] 퍼블리싱 추가
  public/externalLinkGray.svg
  public/placePoint.svg
  src/app/(primary)/_components/FlavorTag.tsx
  src/app/(primary)/_components/Label.tsx
  src/app/(primary)/_components/ReportModal.tsx
  src/app/(primary)/_components/Toggle.tsx
  src/app/(primary)/review/[id]/_components/Comment.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
Labels: Style, Refactor

#63 [#62] 아이콘 파일명 통일
  public/icon/arrow-down-subcoral.svg
  public/icon/arrow-left-subcoral.svg
  public/icon/arrow-left-white.svg
  public/icon/arrow-right-white.svg
  public/icon/close-subcoral.svg
  public/icon/comment-filled-subcoral.svg
  public/icon/comment-outlined-gray.svg
  public/icon/comment-outlined-subcoral.svg
  public/icon/descending-subcoral.svg
  public/icon/edit-outlined-white.svg
  public/icon/ellipsis-darkgray.svg
  public/icon/externallink-outlined-gray.svg
  public/icon/externallink-outlined-white.svg
  public/icon/glass-filled-subcoral.svg
  public/icon/home-outlined-subcoral.svg
  public/icon/like-filled-subcoral.svg
  public/icon/like-filled-white.svg
  public/icon/like-outlined-subcoral.svg
  public/icon/logo-text-subcoral.svg
  public/icon/logo-text-white.svg
  public/icon/menu-subcoral.svg
  public/icon/menu-white.svg
  public/icon/options-subcoral.svg
  public/icon/placepoint-subcoral.svg
  public/icon/search-subcoral.svg
  public/icon/star-filled-subcoral.svg
  public/icon/star-filled-white.svg
  public/icon/star-half-subcoral.svg
  public/icon/star-outlined-subcoral.svg
  public/icon/thumbup-filled-subcoral.svg
  public/icon/thumbup-filled-white.svg
  public/icon/thumbup-outlined-gray.svg
  public/icon/user-outlined-subcoral.svg
  public/next.svg
  public/vercel.svg
  src/app/(primary)/_components/RecentSearch.tsx
  src/app/(primary)/review/[id]/_components/Comment.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/reviews/page.tsx
  src/app/(primary)/user/[id]/_components/LikeBtn.tsx
  src/app/(primary)/user/[id]/_components/ReviewBtn.tsx
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/components/LinkButton.tsx
  src/components/List/ListManager.tsx
  src/components/Navbar.tsx
  src/components/SearchBar.tsx
  src/components/Star.tsx
  src/components/StarRaiting.tsx
Labels: Modify

#66 [#39 ] Review register, modify 퍼블리싱 추가
  public/icon/arrow-right-subcoral.svg
  public/icon/close-white.svg
  public/icon/marker-subcoral.svg
  public/icon/money-subcoral.svg
  public/icon/photo-subcoral.svg
  public/icon/success-subcoral.svg
  public/icon/won-subcoral.svg
  src/app/(primary)/layout.tsx
  src/app/(primary)/review/_components/AlcoholInfo.tsx
  src/app/(primary)/review/_components/ReviewForm.tsx
  src/app/(primary)/review/_components/SelectFlavor.tsx
  src/app/(primary)/review/modify/@modal/(..)flavorTag/page.tsx
  src/app/(primary)/review/modify/@modal/default.tsx
  src/app/(primary)/review/modify/flavorTag/page.tsx
  src/app/(primary)/review/modify/layout.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/@modal/(..)flavorTag/page.tsx
  src/app/(primary)/review/register/@modal/default.tsx
  src/app/(primary)/review/register/flavorTag/page.tsx
  src/app/(primary)/review/register/layout.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  tailwind.config.ts
Labels: Feat, Modify, Style

#71 NavLayout 컴포넌트 추가
  src/app/(primary)/_components/NavLayout.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/ReviewForm.tsx
  src/app/(primary)/review/_components/SelectFlavor.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/components/Navbar.tsx
  tailwind.config.ts
Labels: Style

#77 [#70, #76 ] font size 정의 및 공통 화면 퍼블리싱
  next.config.mjs
  public/icon/comment-outlined-gray.svg
  public/icon/logo-subcoral.svg
  public/icon/logo-white.svg
  src/app/(primary)/_components/EmptyView.tsx
  src/app/(primary)/_components/FlavorTag.tsx
  src/app/(primary)/_components/Header.tsx
  src/app/(primary)/_components/Label.tsx
  src/app/(primary)/_components/LoginModal.tsx
  src/app/(primary)/_components/SubHeader.tsx
  src/app/(primary)/_components/Toggle.tsx
  src/app/(primary)/review/[id]/_components/Comment.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/AlcoholInfo.tsx
  src/app/(primary)/review/_components/ReviewForm.tsx
  src/app/(primary)/review/_components/SelectFlavor.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/reviews/page.tsx
  src/app/not-found.tsx
  src/components/CategoryTitle.tsx
  src/components/HorizontalItem.tsx
  src/components/LinkButton.tsx
  src/components/Loading.tsx
  src/components/Navbar.tsx
  src/components/SearchBar.tsx
  src/components/Star.tsx
  tailwind.config.ts
Labels: Feat, Style

#75 [#60] 토큰 갱신 로직 작성
  next.config.mjs
  src/app/(custom)/login/page.tsx
  src/app/(primary)/_components/HotList.tsx
  src/app/(primary)/search/[category]/page.tsx
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/app/(primary)/user/[id]/_components/UserInfo.tsx
  src/app/(primary)/user/[id]/_constants/index.ts
  src/app/api/AlcholsApi.ts
  src/app/api/AuthApi.ts
  src/app/api/CommonApi.ts
  src/app/api/UserApi.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/token/renew/route.ts
  src/middleware.ts
  src/types/next-auth.d.ts
  src/utils/Storage.ts
  src/utils/TokenService.ts
  src/utils/apiWrapper.ts
  src/utils/fetchWithAuth.ts
  src/utils/getAccessToken.ts
  src/utils/updateCookie.ts
  tsconfig.json
Labels: Feat

#80 [#68] 마이페이지 추가/수정 UI 반영 (1/2)
  package.json
  public/change-profile.svg
  public/icon/close-brightgray.svg
  src/app/(primary)/user/[id]/_components/UserInfo.tsx
  src/app/(primary)/user/[id]/edit/_components/EditForm.tsx
  src/app/(primary)/user/[id]/edit/page.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/components/List/ListItem.tsx
  src/components/OptionDropdown.tsx
  src/style/globals.css
  src/types/next-auth.d.ts
  src/utils/filterNumbers.ts
  yarn.lock
Labels: Modify, Style
