Repository bottle-note/bottle-note-frontend, pull requests merged in 2024-07, with the labels that each got.

#95 [#86, #87, #73, #72, #40, #88 ] Review 상세보기, 작성, 수정, 삭제 API 및 기능 추가
  next.config.mjs
  package.json
  public/icon/Like-outlined-white.svg
  src/app/(primary)/_components/OptionModal.tsx
  src/app/(primary)/_components/ReportModal.tsx
  src/app/(primary)/_components/SubHeader.tsx
  src/app/(primary)/_components/Toggle.tsx
  src/app/(primary)/review/[id]/_components/Comment.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/AddressForm.tsx
  src/app/(primary)/review/_components/AlcoholInfo.tsx
  src/app/(primary)/review/_components/ContentForm.tsx
  src/app/(primary)/review/_components/ImagesForm.tsx
  src/app/(primary)/review/_components/Map.tsx
  src/app/(primary)/review/_components/PriceForm.tsx
  src/app/(primary)/review/_components/RatingForm.tsx
  src/app/(primary)/review/_components/ReviewForm.tsx
  src/app/(primary)/review/_components/SelectFlavor.tsx
  src/app/(primary)/review/_components/TagsForm.tsx
  src/app/(primary)/review/modify/@modal/(..)flavorTag/page.tsx
  src/app/(primary)/review/modify/@modal/default.tsx
  src/app/(primary)/review/modify/flavorTag/page.tsx
  src/app/(primary)/review/modify/layout.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/@modal/(..)flavorTag/page.tsx
  src/app/(primary)/review/register/@modal/default.tsx
  src/app/(primary)/review/register/flavorTag/page.tsx
  src/app/(primary)/review/register/layout.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/api/AlcholsApi.ts
  src/app/api/RateApi.ts
  src/app/api/ReviewApi.ts
  src/components/HorizontalItem.tsx
  src/components/Modal.tsx
  src/constants/common.ts
  src/style/globals.css
  src/types/Alcohol.ts
  src/types/Image.ts
  src/types/Rate.ts
  src/types/Review.ts
  src/utils/S3Upload.ts
  yarn.lock
Labels: Feat, Modify, Style, Docs

#99 [#96 ] review/{reviewId} 기능 구현 및 리팩토링
  public/icon/pick-filled-subcoral.svg
  public/icon/pick-filled-white.svg
  public/icon/pick-outlined-subcoral.svg
  public/icon/pick-outlined-white.svg
  src/app/(primary)/_components/LikeBtn.tsx
  src/app/(primary)/_components/LoginModal.tsx
  src/app/(primary)/_components/PickBtn.tsx
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/AlcoholInfo.tsx
  src/app/(primary)/review/_components/ReviewForm.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/reviews/page.tsx
  src/app/(primary)/user/[id]/_components/LikeBtn.tsx
  src/app/api/AlcholsApi.ts
  src/components/Button.tsx
  src/types/Alcohol.ts
  src/types/Review.ts
  src/utils/shareOrCopy.ts
Labels: Feat, Modify, Style, Refactor

#108 [#104] 로그인 페이지 UI 퍼블리싱
  public/login/loginButton_Naver.svg
  public/login/loginButton_apple.svg
  public/login/loginButton_google.svg
  public/login/loginButton_kakao.svg
  src/app/(custom)/layout.tsx
  src/app/(custom)/login/_components/LoginOptionDropdown.tsx
  src/app/(custom)/login/_components/SocialLoginBtn.tsx
  src/app/(custom)/login/page.tsx
Labels: Modify, Style

#109 [#81] 공지사항 페이지 UI
  src/app/(primary)/announcement/[id]/page.tsx
  src/app/(primary)/announcement/layout.tsx
  src/app/(primary)/announcement/page.tsx
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/app/(primary)/user/[id]/_constants/index.ts
Labels: Modify, Style

#110 [#98] 공통 Modal 기능 구현 및 review에 공통 modal 적용
  .eslintrc.js
  package.json
  src/app/(primary)/_components/LikeBtn.tsx
  src/app/(primary)/_components/LoginModal.tsx
  src/app/(primary)/_components/PickBtn.tsx
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/AlcoholInfo.tsx
  src/app/(primary)/review/_components/SelectFlavor.tsx
  src/app/(primary)/review/_components/TagsForm.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/api/ReviewApi.ts
  src/components/Button.tsx
  src/components/Modal.tsx
  src/components/PageModal.tsx
  src/store/modalStore.ts
  src/style/globals.css
  src/types/Review.ts
  src/utils/shareOrCopy.ts
  yarn.lock
Labels: Feat, Modify, Style, Refactor

#119 [#98] 반영 안된 commit 추가
  src/app/(primary)/_components/LikeBtn.tsx
  src/app/(primary)/_components/PickBtn.tsx
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/AlcoholInfo.tsx
  src/app/(primary)/review/_components/SelectFlavor.tsx
  src/app/(primary)/review/_components/TagsForm.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/components/Modal.tsx
  src/store/modalStore.ts
Labels: Modify, Refactor

#120 [#117] Review 더보기 리스트 공통 컴포넌트 적용 및 API 연동
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/reviews/page.tsx
  src/app/api/ReviewApi.ts
  src/types/Review.ts
  src/types/common.ts
Labels: Feat, Modify, Refactor

#123 [#100 ] Review 상세조회에 댓글, 대댓글 퍼블리싱
  public/icon/arrow-up-subcoral.svg
  src/app/(primary)/review/[id]/_components/Comment.tsx
  src/app/(primary)/review/[id]/_components/CommentInput.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/types/Comment.ts
Labels: Modify, Style

#124 [#122 ] Like API 연결
  src/app/(primary)/_components/LikeBtn.tsx
  src/app/api/ReviewApi.ts
  src/types/Review.ts
Labels: Feat
