Repository bottle-note/bottle-note-frontend, pull requests merged in 2025-06, with the labels that each got.

#455 [#452] 리뷰 스켈레톤 적용
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/form/TagsForm.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/components/Skeletons/ListItemSkeleton.tsx
  src/components/Skeletons/TagSkeleton.tsx
  src/components/Skeletons/custom/AlcoholDetailsSkeleton.tsx
  src/components/Skeletons/custom/ReviewDetailsSkeleton.tsx
Labels: Style, Refactor

#458 [#439] Star 컴포넌트 개선
  pnpm-lock.yaml
  src/app/(primary)/_components/AlcoholCard.tsx
  src/app/(primary)/explore/_components/ReviewCard.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
  src/app/(primary)/user/[id]/my-bottle/_components/RatingsListItem.tsx
  src/components/Star.tsx
Labels: Refactor

#460 [#459] text, style 관련 개선사항
  src/app/(primary)/inquire/[id]/page.tsx
  src/app/(primary)/inquire/page.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/app/(primary)/user/[id]/my-bottle/page.tsx
  src/components/List/List.tsx
  src/components/Skeletons/custom/AlcoholDetailsSkeleton.tsx
  src/components/Skeletons/custom/ReviewDetailsSkeleton.tsx
Labels: Style, Refactor

#463 [Release] 2025-0605:2
  public/icon/ellipsis-vertical-mainGray.svg
  public/icon/star-filled-maingray.svg
  src/app/(primary)/_components/Label.tsx
  src/app/(primary)/explore/_components/ReviewExploreList.tsx
  src/app/(primary)/explore/_components/ReviewListItem.tsx
  src/app/(primary)/explore/_components/SearchBar.tsx
  src/app/(primary)/explore/_components/WhiskeyExploreList.tsx
  src/app/(primary)/explore/_components/WhiskeyListItem.tsx
  src/app/(primary)/explore/page.tsx
  src/app/(primary)/user/[id]/my-bottle/page.tsx
  src/app/api/ExploreApi.ts
  src/components/CategorySelector.tsx
  src/components/List/ListManager.tsx
  src/components/List/_components/ItemImage.tsx
  src/components/List/_components/ItemInfo.tsx
  src/components/List/_components/ItemStats.tsx
  src/components/Navbar.tsx
  src/components/SideFilterDrawer/Accordion.tsx
  src/components/SideFilterDrawer/index.tsx
  src/constants/common.ts
  src/styles/themeColors.ts
  src/styles/themeFontSizes.ts
Labels: deploy

#478 [Release] 2025-0612:1
  public/bannerImg/bottleNote-banner.png
  public/bannerImg/rain-banner.png
  public/bannerImg/summer-banner.png
  public/bottle_note_logo_main.svg
  src/app/(primary)/_components/Header.tsx
  src/app/(primary)/_components/MainCarousel.tsx
  src/app/(primary)/_components/TimeLineItem.tsx
  src/app/(primary)/history/_components/HistoryDescription.tsx
  src/app/(primary)/history/_components/Icons.tsx
  src/app/(primary)/history/_components/filter/FilterDateRange.tsx
  src/app/(primary)/history/_components/filter/FilterGroup.tsx
  src/app/(primary)/history/_components/filter/FilterOption.tsx
  src/app/(primary)/history/_components/filter/FilterSideModal.tsx
  src/app/(primary)/history/_components/filter/ToggleContainer.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/page.tsx
  src/components/Search/SearchBar.tsx
  src/constants/history.ts
  src/constants/home.ts
  src/constants/routes.ts
  tailwind.config.ts
Labels: deploy

#479 [#355, #356, #357] 스타일 수정
  src/app/(primary)/_components/CategoryList.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/user/[id]/_components/HistoryOverview.tsx
  src/app/(primary)/user/[id]/_components/UserInfo.tsx
  src/app/(primary)/user/[id]/page.tsx
Labels: Style

#480 리드미 업데이트
  README.md
Labels: Docs

#486 [#152] 둘러보기 스타일 수정 + 마이보틀 스타일 수정
  public/icon/rating-count-gray.svg
  src/app/(primary)/explore/_components/WhiskeyListItem.tsx
  src/app/(primary)/user/[id]/_components/HistoryOverview.tsx
  src/app/(primary)/user/[id]/_components/UserInfo.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/components/List/_components/ItemStats.tsx
Labels: Style

#487 [#483] 공통 header 오류 수정
  public/icon/menu-subcoral.svg
  src/app/(primary)/_components/SidebarHeader.tsx
  src/app/(primary)/_components/SubHeader.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/review/_components/ReviewHeaderLayout.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/[category]/[id]/page.tsx
Labels: Fix, Refactor

#491 [Fix] Applied memoization to child components of review
  src/app/(primary)/_components/AlcoholImage.tsx
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
Labels: Fix

#492 [Release] 2025-0619:2
  src/app/(primary)/_components/AlcoholImage.tsx
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
Labels: deploy

#493 [#484] 리뷰 수정 v1.1
  src/app/(primary)/review/_components/AlcoholInfo.tsx
  src/app/(primary)/review/_components/ReviewHeaderLayout.tsx
  src/app/(primary)/review/_components/form/AddressForm.tsx
  src/app/(primary)/review/_components/form/ContentForm.tsx
  src/app/(primary)/review/_components/form/ImagesForm.tsx
  src/app/(primary)/review/_components/form/PriceForm.tsx
  src/app/(primary)/review/_components/form/ReviewForm.tsx
  src/app/(primary)/review/_components/form/TagsForm.tsx
  src/app/(primary)/review/modify/page.tsx
  src/app/(primary)/review/register/page.tsx
  src/app/(primary)/search/page.tsx
Labels: Modify, Style
