Repository bottle-note/bottle-note-frontend, pull requests merged in 2025-05, with the labels that each got.

#410 [#407] 리뷰 이미지 버그 및 스타일 수정
  src/app/(primary)/history/_components/filter/FilterSideModal.tsx
  src/app/(primary)/history/page.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/review/_components/OptionsContainer.tsx
Labels: Fix, Style

#417 [#414, #359, #351] 검색페이지 카테고리 탭, 훅 관련 컴포넌트 리팩토링
  src/app/(primary)/page.tsx
  src/app/(primary)/search/page.tsx
  src/components/CategorySelector.tsx
  src/components/List/List.tsx
  src/components/SectionTitle.tsx
  src/hooks/useCategory.ts
  src/hooks/useTab.ts
Labels: Refactor

#421 [Release] 2025-0509 :1
  package.json
  src/app/(primary)/_components/AlcoholCard.tsx
  src/app/(primary)/_components/PopularList.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/search/page.tsx
  src/app/api/AlcholsApi.ts
  src/components/CategorySelector.tsx
  src/components/List/List.tsx
  src/components/SectionTitle.tsx
  src/components/Tab/variants/BookmarkTab.tsx
  src/hooks/useCategory.ts
  src/hooks/useTab.ts
  yarn.lock
Labels: deploy

#425 [#371] 환경변수 분리에 따른 build 커맨드 수정
  package.json
  yarn.lock
Labels: Docs

#426 [#371] OS 상관없이 일관된 환경변수 사용을 위한 cross-env 추가 적용
  package.json
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  yarn.lock
Labels: Fix

#430 [#429] 기록 페이지 스켈레톤 적용 및 스켈레톤 리팩토링
  package.json
  src/app/(primary)/_components/PopularList.tsx
  src/app/(primary)/history/_components/HistoryEmptyState.tsx
  src/app/(primary)/history/_components/Timeline.tsx
  src/app/(primary)/history/page.tsx
  src/app/(primary)/user/[id]/_components/Timeline.tsx
  src/components/Skeletons/SkeletonBase.tsx
  src/components/Skeletons/custom/PopularSkeleton.tsx
  src/components/Skeletons/custom/TimelineSkeleton.tsx
  src/hooks/usePopularList.ts
  src/types/Popular.ts
Labels: Feat, Style, Refactor

#436 [#424, #349] 검색 페이지 책갈피 적용, 리뷰 디테일 디자인 및 버그 수정
  public/fonts/SUIT-Bold.otf
  public/fonts/SUIT-ExtraBold.otf
  public/fonts/SUIT-Medium.otf
  public/fonts/SUIT-SemiBold.otf
  src/app/(primary)/_components/FlavorTag.tsx
  src/app/(primary)/_components/LikeBtn.tsx
  src/app/(primary)/_components/PickBtn.tsx
  src/app/(primary)/_components/Toggle.tsx
  src/app/(primary)/history/_components/Timeline.tsx
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/review/[id]/_components/Reply/Reply.tsx
  src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
  src/app/(primary)/review/[id]/_components/Reply/ReplyList.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/page.tsx
  src/components/List/List.tsx
  src/components/SectionTitle.tsx
  src/components/Skeletons/custom/TimelineSkeleton.tsx
  src/components/Star.tsx
  src/components/Tab/index.tsx
  src/components/Tab/variants/BookmarkTab.tsx
  src/style/globals.css
  tailwind.config.ts
Labels: Feat, Modify, Fix, Style

#440 [#438] '최근에 본 위스키' 수정
  src/app/(primary)/_components/AlcoholCard.tsx
  src/app/(primary)/_components/PopularList.tsx
  src/components/Skeletons/custom/PopularSkeleton.tsx
  src/components/Star.tsx
Labels: Modify, Style

#435 dev to main
  .github/workflows/build_validation.yml
  public/fonts/SUIT-Bold.otf
  public/fonts/SUIT-ExtraBold.otf
  public/fonts/SUIT-Medium.otf
  public/fonts/SUIT-SemiBold.otf
  src/app/(primary)/_components/AlcoholCard.tsx
  src/app/(primary)/_components/FlavorTag.tsx
  src/app/(primary)/_components/LikeBtn.tsx
  src/app/(primary)/_components/PickBtn.tsx
  src/app/(primary)/_components/PopularList.tsx
  src/app/(primary)/_components/Toggle.tsx
  src/app/(primary)/history/_components/Timeline.tsx
  src/app/(primary)/review/[id]/_components/AlcoholInfo.tsx
  src/app/(primary)/review/[id]/_components/Reply/Reply.tsx
  src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
  src/app/(primary)/review/[id]/_components/Reply/ReplyList.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/review/[id]/page.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/search/page.tsx
  src/components/List/List.tsx
  src/components/Navbar.tsx
  src/components/SectionTitle.tsx
  src/components/Skeletons/custom/PopularSkeleton.tsx
  src/components/Skeletons/custom/TimelineSkeleton.tsx
  src/components/Star.tsx
  src/components/Tab/index.tsx
  src/components/Tab/variants/BookmarkTab.tsx
  src/style/globals.css
  tailwind.config.ts
Labels: deploy

#447 cross-platform 지원을 위한 shx 적용
  package.json
  pnpm-lock.yaml
Labels: Feat

#453 [#342] 히스토리 filter api 호출 개선
  src/app/(primary)/history/_components/HistoryEmptyState.tsx
  src/app/(primary)/history/_components/Timeline.tsx
  src/app/(primary)/history/page.tsx
  src/components/Search/SearchBar.tsx
Labels: Fix, Refactor
