Repository bottle-note/bottle-note-frontend, pull requests merged in 2025-02, with the labels that each got.

#237 [#131] 프로필 수정 카메라, 앨범 접근 기능 추가 개발 #131
  .github/workflows/deploy_workflow.yml
  package.json
  src/app/(custom)/layout.tsx
  src/app/(custom)/login/page.tsx
  src/app/(primary)/layout.tsx
  src/app/(primary)/user/[id]/_components/ProfileImage.tsx
  src/app/(primary)/user/[id]/_components/UserInfo.tsx
  src/app/(primary)/user/[id]/edit/_components/EditForm.tsx
  src/app/(primary)/user/[id]/edit/page.tsx
  src/app/api/UserApi.ts
  src/hooks/useWebViewInit.ts
  src/hooks/useWebviewCamera.ts
  src/types/types.d.ts
  src/utils/base64ToFile.ts
  src/utils/flutterUtil.ts
  yarn.lock
Labels: Feat

#239 [#232 ] 히스토리 퍼블리싱 추가 및 버그 수정
  .github/workflows/deploy_workflow.yml
  mock/history.ts
  package.json
  public/icon/arrow-down-darkgray.svg
  public/icon/calendar-subcoral.svg
  public/icon/check-white.svg
  public/icon/close-gray.svg
  public/icon/document-outlined-subcoral.svg
  public/icon/filter-subcoral.svg
  public/icon/history/bottle-filled-subcoral.svg
  public/icon/history/like_unfilled_subcoral.svg
  public/icon/history/pick_filled_subcoral.svg
  public/icon/history/pick_unfilled_subcoral.svg
  public/icon/history/rating_filled_blue.svg
  public/icon/history/rating_filled_red.svg
  public/icon/history/rating_filled_subcoral.svg
  public/icon/history/rating_unfilled_subcoral.svg
  public/icon/history/reply_unfilled_subcoral.svg
  public/icon/history/review_subcoral.svg
  public/icon/history/review_white.svg
  src/app/(primary)/_components/TimeLineItem.tsx
  src/app/(primary)/history/_components/filter/FilterContainer.tsx
  src/app/(primary)/history/_components/filter/FilterOption.tsx
  src/app/(primary)/history/_components/filter/FilterSideModal.tsx
  src/app/(primary)/history/_components/filter/Icons.tsx
  src/app/(primary)/history/_components/filter/ToggleContainer.tsx
  src/app/(primary)/history/page.tsx
  src/app/(primary)/inquire/[id]/page.tsx
  src/app/(primary)/review/[id]/_components/Reply/Reply.tsx
  src/app/(primary)/review/[id]/_components/ReviewDetails.tsx
  src/app/(primary)/search/[category]/[id]/_components/AlcoholBox.tsx
  src/app/(primary)/search/[category]/[id]/_components/Review.tsx
  src/app/(primary)/user/[id]/_components/Timeline.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/components/DateRangePicker.tsx
  src/components/List/BoardListItem.tsx
  src/components/Navbar.tsx
  src/components/Search/SearchContainer.tsx
  src/constants/history.ts
  src/constants/historyType.tsx
  src/style/globals.css
  src/types/FormatDate.ts
  src/types/History.ts
  src/utils/formatDate.ts
  yarn.lock
Labels: Feat, Modify, Fix, Style

#244 [Hotfix] User 페이지에 히스토리 컴포넌트와 sidebarHeader 겹침 수정
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/app/(primary)/user/[id]/_components/Timeline.tsx
  src/app/(primary)/user/[id]/page.tsx
Labels: Fix

#245 regular release: 2025-02-11:open
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/app/(primary)/user/[id]/_components/Timeline.tsx
  src/app/(primary)/user/[id]/page.tsx
  src/app/api/AuthApi.ts
  src/components/Navbar.tsx
  src/utils/checkTokenValidity.ts
  src/utils/fetchWithAuth.ts
Labels: deploy

#243 Review 스타일, 기능 QC_1-1
  .github/empty-231.txt
  .github/workflows/build_validation.yml
  src/app/(primary)/_components/LoginModal.tsx
  src/app/(primary)/review/_components/form/TagsForm.tsx
  src/app/(primary)/review/layout.tsx
  src/components/HoverTouchBox.tsx
  src/components/LinkButton.tsx
  src/store/tooltipStore.ts
Labels: Modify, Style

#257 [Hotfix] 별점, 검색 list item 레이아웃 깨짐 및 navbar active 조건 수정
  src/components/List/ListItem.tsx
  src/components/List/_components/ItemInfo.tsx
  src/components/Navbar.tsx
Labels: Fix

#264 [Release] 2025-0213 - 01
  src/app/(primary)/review/[id]/_components/Reply/ReplyInput.tsx
  src/app/(primary)/review/_components/OptionsContainer.tsx
  src/app/(primary)/user/[id]/_components/SidebarHeader.tsx
  src/components/BackDrop.tsx
  src/style/globals.css
Labels: deploy

#269 [#113 ] 마이 히스토리, 히스토리 페이지 API 연동
  mock/history.ts
  src/app/(primary)/_components/TimeLineItem.tsx
  src/app/(primary)/history/_components/HistoryEmptyState.tsx
  src/app/(primary)/history/_components/filter/DateRangeFilter.tsx
  src/app/(primary)/history/_components/filter/FilterContainer.tsx
  src/app/(primary)/history/_components/filter/FilterOption.tsx
  src/app/(primary)/history/_components/filter/FilterSideModal.tsx
  src/app/(primary)/history/_components/filter/HistoryDescription.tsx
  src/app/(primary)/history/page.tsx
  src/app/(primary)/user/[id]/_components/Timeline.tsx
  src/app/api/HistoryApi.ts
  src/components/BackDrop.tsx
  src/components/DateRangePicker.tsx
  src/components/Search/SearchBar.tsx
  src/components/Search/SearchContainer.tsx
  src/constants/history.ts
  src/constants/historyType.tsx
  src/queries/usePaginatedQuery.ts
  src/store/historyFilterStore.ts
  src/types/History.ts
  src/utils/historyFilter.ts
  src/utils/historyUtils.ts
Labels: Feat, Modify, Fix, Style, Refactor

#265 modify: update Dockerfile to support sharp and standalone mode
  .github/empty-231.txt
  .github/merge-1.txt
  Dockerfile
Labels: deploy
